version: 2

sphinx:
  configuration: docs/conf.py  # required key, but we don't rely on Sphinx

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    rust: latest
  commands:
    - cargo install mdbook
    - rustup component add rustfmt
    - mdbook build book --dest-dir $READTHEDOCS_OUTPUT/html