version: 2

build:
  os: ubuntu-lts-latest
  tools:
    rust: latest  # Ensures Rust toolchain

jobs:
  install:
    - cargo install mdbook
    - rustup component add rustfmt  # Optional, for pretty code blocks
  build:
    html:
      - mdbook build book --dest-dir $READTHEDOCS_OUTPUT/html