version: 2

build:
  os: ubuntu-22.04
  tools:
    rust: latest
  commands:
    - cargo install mdbook
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - mdbook build book --dest-dir $READTHEDOCS_OUTPUT/html